### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by SandipanGuha** [adamantonio/gooeypie#1]
### I have installed gooeypie successfully and trying to run my first program.
**But I am getting this error :** 
`ModuleNotFoundError: No module named 'tkinter'`

<_**main.py**_>
```
import gooeypie as gp
app = gp.GooeyPieApp("Test")
app.width=300
app.run()
```
<_**Terminal output**_>
```
PS C:\Users\Sandipan\OneDrive\GooeyPie> & "C:/Program Files/Python310/python.exe" c:/Users/Sandipan/OneDrive/GooeyPie/test/main.py
Traceback (most recent call last):
  File "c:\Users\Sandipan\OneDrive\GooeyPie\test\main.py", line 1, in <module>
    import gooeypie as g
  File "C:\Users\Sandipan\AppData\Roaming\Python\Python310\site-packages\gooeypie\__init__.py", line 2, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'
PS C:\Users\Sandipan\OneDrive\GooeyPie> & "C:/Program Files/Python310/python.exe" c:/Users/Sandipan/OneDrive/GooeyPie/test/main.py
Traceback (most recent call last):
  File "c:\Users\Sandipan\OneDrive\GooeyPie\test\main.py", line 1, in <module>
    import gooeypie as gp
  File "C:\Users\Sandipan\AppData\Roaming\Python\Python310\site-packages\gooeypie\__init__.py", line 2, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'

```
Checking if GooeyPie installed successfully:
<_**CMD output**_>
```
C:\Users\Sandipan>pip install gooeypie
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gooeypie in c:\users\sandipan\appdata\roaming\python\python310\site-packages (0.6.0)
Requirement already satisfied: pillow in c:\users\sandipan\appdata\roaming\python\python310\site-packages (from gooeypie) (9.1.0)
```

**Comment by adamantonio** [comment]
The error message indicates that your Python installation does not have the tkinter module installed, which is an included library for creating user interfaces in Python and is required by GooeyPie. I can see that you have a Windows installation - this means you should be able take the following steps to install tkinter:


  1.  Press the start button, type in 'Add or Remove Programs' and press enter.
  2.  Find Python in the list of installed applications and click 'Modify'
  3.  Ensure that 'tcl/tk and IDLE' are checked as in the screenshot below and click next.

***@***.***





From: Sandipan Guha ***@***.***>
Sent: Monday, 28 November 2022 3:14 PM
To: adamantonio/gooeypie ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adamantonio/gooeypie] ModuleNotFoundError: No module named 'tkinter' (Issue #1)

I have installed gooeypie successfully and trying to run my first program.

But I am getting this error :
<main.py>

import gooeypie as gp

app = gp.GooeyPieApp("Test")

app.width=300

app.run()

<Terminal output>

PS C:\Users\Sandipan\OneDrive\GooeyPie> & "C:/Program Files/Python310/python.exe" c:/Users/Sandipan/OneDrive/GooeyPie/test/main.py

Traceback (most recent call last):

  File "c:\Users\Sandipan\OneDrive\GooeyPie\test\main.py", line 1, in <module>

    import gooeypie as g

  File "C:\Users\Sandipan\AppData\Roaming\Python\Python310\site-packages\gooeypie\__init__.py", line 2, in <module>

    import tkinter

ModuleNotFoundError: No module named 'tkinter'

PS C:\Users\Sandipan\OneDrive\GooeyPie> & "C:/Program Files/Python310/python.exe" c:/Users/Sandipan/OneDrive/GooeyPie/test/main.py

Traceback (most recent call last):

  File "c:\Users\Sandipan\OneDrive\GooeyPie\test\main.py", line 1, in <module>

    import gooeypie as gp

  File "C:\Users\Sandipan\AppData\Roaming\Python\Python310\site-packages\gooeypie\__init__.py", line 2, in <module>

    import tkinter

ModuleNotFoundError: No module named 'tkinter'



Checking if GooeyPie installed successfully:
<CMD output>

C:\Users\Sandipan>pip install gooeypie

Defaulting to user installation because normal site-packages is not writeable

Requirement already satisfied: gooeypie in c:\users\sandipan\appdata\roaming\python\python310\site-packages (0.6.0)

Requirement already satisfied: pillow in c:\users\sandipan\appdata\roaming\python\python310\site-packages (from gooeypie) (9.1.0)

-
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadamantonio%2Fgooeypie%2Fissues%2F1&data=05%7C01%7Cantonioa%40abbotsleigh.nsw.edu.au%7Ca81fa208da4b40de2d1808dad0f6f8cb%7C6c1a13b0f153457faaf1432df7641ddf%7C1%7C0%7C638052056409996275%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Iuf2y%2B%2Fok05uOwUW7ogX7IuXr9Q6IcCzgmVu8jkD5ZA%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALRW3OJYDPRX43DCCWSIVLLWKQWQHANCNFSM6AAAAAASM4UEJQ&data=05%7C01%7Cantonioa%40abbotsleigh.nsw.edu.au%7Ca81fa208da4b40de2d1808dad0f6f8cb%7C6c1a13b0f153457faaf1432df7641ddf%7C1%7C0%7C638052056409996275%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kGH4TiDE2JcRpd2XPINH63X7uzzPmrrMy1ALDo0Wvu0%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>

________________________________

Abbotsleigh values the privacy of its community. This email and its attachments are confidential. If you have received this email in error please preserve its confidentiality, notify Abbotsleigh by phone (61 2 9473 7750) or email at ***@***.*** and permanently delete it. Any opinions expressed in this email are those of the sender, except where the sender, with authority, states them to be the opinions of Abbotsleigh.

Please consider our environment before printing this email.

**Comment by adamantonio** [comment]
Please update your Python installation to include tcl/Tk.
